name = "zen-connect"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Production environment variables
[env.production.vars]
NEXT_PUBLIC_APP_ENV = "production"
NEXT_PUBLIC_API_URL = "https://api.zen-connect.com"  # 本番API URL（未設定時はダミー）

# Preview environment variables  
[env.preview.vars]
NEXT_PUBLIC_APP_ENV = "preview"
NEXT_PUBLIC_API_URL = "https://api-staging.zen-connect.com"  # ステージング用（未設定時はダミー）